# Generated by Django 5.1 on 2024-11-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('intrumento', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=250)),
                ('experiencia', models.CharField(max_length=50)),
            ],
        ),
    ]
